### ISSUE TITLE
Problem with bowtie2

### ISSUE THREAD

**Issue by franzilie** [sternberglab/INTEGRATE-guide-RNA-tool#2]
Hello,

I am trying to run CAST. Bowtie is installed and in the PATH, but I get following error:
Traceback (most recent call last):
  File "/Users/frle0002/CAST-guide-RNA-tool-master/src/bowtie.py", line 25, in build
    subprocess.run(build_command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
  File "/Users/frle0002/opt/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie2-build / /Users/frle0002/CAST-guide-RNA-tool-master/assets/bowtie/index' returned non-zero exit status 245.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/frle0002/CAST-guide-RNA-tool-master/spacer_gen.py", line 112, in <module>
    spacer_gen({"output_path": output_path, "genbank_files": genbank_files, "genome_fasta_files": genome_fasta_files, "nonessential_only": nonessential_only, "spacers_per_region": spacers_per_region, "GC_requirement": GC_requirement, "genbank_ids": genbank_ids, "email": email, "region_type": region_type, "overlapping_spacers": overlapping_spacers, "coding_spacer_direction": coding_spacer_direction, "start_pct": start_pct, "end_pct": end_pct, "target_locus_tags_csv": target_locus_tags_csv, "noncoding_boundary": noncoding_boundary, "custom_regions_csv": custom_regions_csv, "custom_sequences": custom_sequences})
  File "/Users/frle0002/CAST-guide-RNA-tool-master/src/main.py", line 75, in spacer_gen
    bowtie_build(without_filetype, fasta_file=Path(genome_fasta_file).absolute())
  File "/Users/frle0002/CAST-guide-RNA-tool-master/src/bowtie.py", line 27, in build
    raise Exception(f"Error running bowtie, see Installation notes in the README: \n{e}")

Do you have an idea what is wrong? Thanks a lot!

**Comment by dgelsin** [comment]
Hi @franzilie, thanks for using our program and for reaching out. I'm sorry you're encountering errors so far. What would help me debug is to provide the exact command you are using and to provide the input parameters you are using. 

At first glance, it looks like a bowtie2 installation issue. How did you install bowtie2? Is it possible you have 2 versions installed or the wrong Perl binaries?

**Comment by dgelsin** [comment]
Also @caacree, what do you think?

**Comment by caacree** [comment]
I've only seen that come up when it can't find `bowtie` in the system PATH; if you're running this from a conda environment or other container where bowtie is installed, it still won't work unless it is in the system path. Some of our newer scripts are now able to be fully run in virtual environments like conda, but this one is not. 

The `non-zero exit status 245` might indicate something else though, I can't find any information about that error code and don't think I've seen it before. It's tough to say from the information here.

**Comment by franzilie** [comment]
Hi,

thanks a lot for your answer. Bowtie is only installed once, in the path and runs without a problem otherwise.  I run everything with the standard parameters on a genome in fasta format and and a custom sequence.

**Comment by caacree** [comment]
@franzilie 
It doesn't seem to be printing the full error traceout; can you add a line to the source code just above the error (File "/Users/frle0002/CAST-guide-RNA-tool-master/src/bowtie.py", line 27), so it looks like
```
except Exception as e:
    print(e)
    raise Exception(f"Error running bowtie, see Installation notes in the README: \n{e}")
```
and run it again to see if that gives any more detail?
